import os
import json
import httpx

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")

async def call_openrouter(messages: list) -> str:
    if not OPENROUTER_API_KEY:
        return "Mock Response (No API Key): 4"

    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "http://localhost:8000"
    }
    payload = {
        "model": "openai/gpt-oss-120b",
        "messages": messages
    }
    
    async with httpx.AsyncClient() as client:
        response = await client.post(url, headers=headers, json=payload, timeout=60.0)
        response.raise_for_status()
        data = response.json()
        return data["choices"][0]["message"]["content"]

async def chat_with_board(user_message: str, current_board: dict, conversation_history: list = None) -> dict:
    if not OPENROUTER_API_KEY:
        # Mock logic to pass MVP without key
        if "fix login bug" in user_message.lower():
            current_board["cards"]["mock-card-1"] = {"id": "mock-card-1", "title": "Fix login bug", "details": "Generated by mock."}
            current_board["columns"][0]["cardIds"].append("mock-card-1")
            return {"message": "I've created a card to fix the login bug.", "boardUpdate": current_board}
        return {"message": f"Mock AI Response (No API Key). You said: {user_message}", "boardUpdate": None}

    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "http://localhost:8000"
    }
    
    system_prompt = f"""You are a helpful AI project manager assistant.
The user is currently viewing their Kanban board.
Current Board JSON: {json.dumps(current_board)}

You MUST respond strictly in the following JSON format:
{{
  "message": "Your text response to the user.",
  "boardUpdate": null // OR provide the COMPLETELY FULL updated Board JSON if you are making changes to the board based on the user's request. It must contain the 'columns' array and 'cards' object.
}}

CRITICAL RULES FOR MOVING CARDS:
- If moving a card from Column A to Column B, you MUST remove its ID from Column A's `cardIds` array.
- You MUST add the ID strictly exactly once to Column B's `cardIds` array.
- Do NOT duplicate the ID across multiple columns. A card ID can only exist in ONE column.
Do NOT wrap the response in markdown blocks. Output raw parseable JSON only.
"""
    messages = [{"role": "system", "content": system_prompt}]
    if conversation_history:
        messages.extend(conversation_history)
    messages.append({"role": "user", "content": user_message})
    
    payload = {
        "model": "openai/gpt-oss-120b",
        "messages": messages,
        # Stripped JSON Object response format since some OSS OpenRouter models throw 400s for it
    }
    
    async with httpx.AsyncClient() as client:
        response = await client.post(url, headers=headers, json=payload, timeout=60.0)
        response.raise_for_status()
        data = response.json()
        raw_content = data["choices"][0]["message"]["content"]
        
        try:
            return json.loads(raw_content.strip("```json\n").strip("```"))
        except json.JSONDecodeError:
            return {"message": "AI returned malformed JSON: " + raw_content, "boardUpdate": None}
